### ISSUE TITLE
How to set custom nodeSelector for deployments

### ISSUE THREAD

**Issue by tech348712013870132** [kubeflow/kfctl#283]
Is it possible to say kfctl that all deployments should be created with a specific and custom nodeSelector on setup (context: kubeflow)?
We are using the latest kfctl_istio_dex.yaml (kubeflow) and kfctl version for our kubernetes setup but not yet figured out how to accomplish this (or have we maybe overlooked the possibility?)

We would really love to see an implementation for this feature :)

**Comment by jlewi** [comment]
Is this not supported out of the box today.  Following a shift left philosophy you could do this by generating the YAML for all the kustomize applications and then adding a node selector.

You might want to investigate creating a custom kustomize transformer (or plugin) in order to recourse through all the pods and add a node selector.
